name: Build and Push To ECR

on:
  workflow_dispatch:
    inputs:
      service_choice:
        description: 'Select the service to Build and push'
        required: true
        type: choice
        options:
          - api
          - worker
          - dashboard

env:
  AWS_REGION: eu-west-2                 

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
    -  name: checkout code
       uses: actions/checkout@v4
       

    -  name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
        audience: sts.amazonaws.com
        aws-region: eu-west-2
        role-to-assume: arn:aws:iam::306758374042:role/cicd-role

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    
    - name: Build, tag & push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
        SERVICE: ${{ inputs.service_choice }}
      run: |
        if [ "$SERVICE" = "api" ]; then
          ECR_REPOSITORY="api_ecr"
          CONTEXT_PATH="application/app"
          DOCKERFILE_PATH="application/app/Dockerfile"
        
        elif [ "$SERVICE" = "dashboard" ]; then
          ECR_REPOSITORY="dashboard_ecr"
          CONTEXT_PATH="application/services/dashboard"
          DOCKERFILE_PATH="application/services/dashboard/Dockerfile"
        
        elif [ "$SERVICE" = "worker" ]; then
          ECR_REPOSITORY="worker_ecr"
          CONTEXT_PATH="application/services/worker"
          DOCKERFILE_PATH="application/services/worker/Dockerfile"
        fi

        echo "Selected Service: $SERVICE"
        echo "Target Repository: $ECR_REPOSITORY"
        echo "Context Path: $CONTEXT_PATH"
        echo "Dockerfile Path: $DOCKERFILE_PATH"


        docker buildx build \
          --cache-from=type=gha,scope=$SERVICE \
          --cache-to=type=gha,mode=max,scope=$SERVICE \
          -f $DOCKERFILE_PATH \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --push $CONTEXT_PATH
        
