name: Terraform Destroy Pipeline
on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm"
        required: true
        default: "NO"


permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_WORKING_DIR: infra

jobs:
  destroy:
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::306758374042:role/cicd-role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Destroy Plan
        working-directory: ./infra
        run: terraform plan "-destroy" "-input=false" "-no-color"
        env:
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_rds_username: ${{ secrets.RDS_USERNAME }}

      - name: Terraform Destroy Apply
        working-directory: ./infra
        run: terraform destroy "-auto-approve" "-input=false"
        env:
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_rds_username: ${{ secrets.RDS_USERNAME }}
