name: Terraform Plan

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_WORKING_DIR: infra

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::306758374042:role/cicd-role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./infra
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ./infra
        run: terraform validate

      
      - name: Terraform Plan
        working-directory: ./infra
        run: |
          terraform plan -input=false -no-color > plan.out 2>&1 || true
          cat plan.out
          echo "=== TAIL OF LOG ==="
          tail -n 30 plan.out
          if grep -q "Error:" plan.out || grep -q "panic:" plan.out; then exit 1; fi

        env:
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_rds_username: ${{ secrets.RDS_USERNAME }}


